name: Build

on:
  workflow_dispatch: { }

jobs:
  build:
    name: build
    runs-on: ubuntu-22.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: tonybogdanov/fps:latest
  purge_workflow_runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
    steps:
      - name: Setup
        run: sudo apt-get install -y jq
      - env:
          GH_TOKEN: ${{ github.token }}
        name: Purge
        run: |
          gh api repos/TonyBogdanov/fps/actions/runs --paginate |\
          jq '.workflow_runs[] | .id' |\
          xargs -t -I{} sh -c "gh api -X DELETE /repos/TonyBogdanov/fps/actions/runs/{} || true"
